url: http://keeg0222.github.io
baseurl: /KurtisAndCloud/

# Site settings
title: Kurtis And Cloud | Home
email: kurtisandcloud@gmail.com
description: "Kurtis And Cloud"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0099FF
  secondary: 007ACC 
  secondary-dark: 333

# Team names, titles and social links
people:

- name:

- name: Kurtis Heild
  pic: 2
  position: Drone Photographer and Cinamatographer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
